%YAML:1.0

# Project
project_name: "lvi_sam"

#common parameters
imu_topic: "/imu/data"
image_topic: "/F1/image_mono"
point_cloud_topic: "/lidar_h/velodyne_points"
# point_cloud_topic: "lvi_sam/lidar/deskew/cloud_deskewed"

# Lidar Params
use_lidar: 1                     # whether use depth info from lidar or not
lidar_skip: 3                    # skip this amount of scans
align_camera_lidar_estimation: 1 # align camera and lidar estimation for visualization

# lidar to camera extrinsic
lidar_to_cam_tx: -0.002368714880683
lidar_to_cam_ty: -0.0253357
lidar_to_cam_tz: -0.1522565
lidar_to_cam_rx: 1.6118659
lidar_to_cam_ry: 0.0167622
lidar_to_cam_rz: 1.568448

# imu to lidar extrinsic
imu_to_lidar_tx: -0.0346099
imu_to_lidar_ty: -0.00230394
imu_to_lidar_tz: -0.0107052
imu_to_lidar_rx: 3.12341
imu_to_lidar_ry: -0.0350578
imu_to_lidar_rz: 3.1291

# camera model
model_type: KANNALA_BRANDT
camera_name: camera

# Mono camera config
image_width: 2048
image_height: 1536
projection_parameters:
   k2: 0.0038663000000000000318
   k3: 0.024943365054747011073
   k4: -0.020060572215327615586
   k5: 0.0046978196460776200025
   mu: 763.15899999999999181
   mv: 762.40844040460251563
   u0: 1017.926230276339993
   v0: 791.39848788627455178

fisheye_mask: "/config/ig2/fisheye_mask_2048x1536.jpg"

#imu parameters      The more accurate parameters you provide, the worse performance
acc_n: 0.02387       # accelerometer measurement noise standard deviation.
gyr_n: 0.00192       # gyroscope measurement noise standard deviation.
acc_w: 0.03066       # accelerometer bias random work noise standard deviation.
gyr_w: 0.00155       # gyroscope bias random work noise standard deviation.
g_norm: 9.8050       #
imu_hz: 200         # frequency of imu

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning. 
#Rotation from camera frame to imu frame, imu^R_cam
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.0100912,  0.00595533, -0.999931,
         -0.999948,   0.00139603, -0.010083,
          0.00133588, 0.999981,    0.00596911]
#Translation from camera frame to imu frame, imu^T_cam
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [-0.186307, -0.00218688, 0.0142954]

#feature tracker parameters
max_cnt: 100            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 0                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 1             # if image is too dark or light, trun on equalize to find enough features
fisheye: 1              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points

#optimization parameters
max_solver_time: 0.035   # max solver itration time (ms), to guarantee real time
max_num_iterations: 8    # max solver itrations, to guarantee real time
keyframe_parallax: 30.0  # keyframe selection threshold (pixel)

#unsynchronization parameters
estimate_td: 0           # online estimate time offset between camera and imu
td: 0                    # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#rolling shutter parameters
rolling_shutter: 0       # 0: global shutter camera, 1: rolling shutter camera
rolling_shutter_tr: 0    # unit: s. rolling shutter read out time per frame (from data sheet). 

#loop closure parameters
loop_closure: 1                    # start loop closure
skip_time: 0.0
skip_dist: 0.0
debug_image: 0                      # save raw image in loop detector for visualization prupose; you can close this function by setting 0 
match_image_scale: 0.5
vocabulary_file: "/config/brief_k10L6.bin"
brief_pattern_file: "/config/brief_pattern.yml"
